"""Read the build-time candidate identity embedded in a clean wheel."""

from __future__ import annotations

import json
import base64
import csv
import hashlib
import io
import os
from importlib.metadata import distribution, distributions
from importlib.resources import files
from pathlib import Path
from typing import Iterable, Sequence


def record_projection_sha256(rows: Iterable[Sequence[str]]) -> str:
    """Hash candidate wheel members, excluding installer-owned RECORD additions."""

    installer_owned = {"INSTALLER", "REQUESTED", "direct_url.json", "uv_cache.json"}
    projection = sorted(
        [str(value) for value in row]
        for row in rows
        if len(row) == 3
        and bool(row[1])
        and not row[0].startswith(("bin/", "../../../bin/"))
        and not row[0].endswith(".pyc")
        and row[0].rsplit("/", 1)[-1] not in installer_owned
    )
    if not projection:
        raise RuntimeError("Candidate RECORD projection has no wheel members.")
    encoded = json.dumps(projection, separators=(",", ":"), sort_keys=False).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def installed_dependency_projection() -> dict[str, object]:
    """Return the exact installed name/version projection used by the Account process."""

    packages = sorted(
        {
            str(item.metadata["Name"]).lower().replace("_", "-"): item.version
            for item in distributions()
            if item.metadata.get("Name")
        }.items()
    )
    encoded = json.dumps(packages, separators=(",", ":")).encode("utf-8")
    return {
        "packages": [{"name": name, "version": version} for name, version in packages],
        "sha256": hashlib.sha256(encoded).hexdigest(),
    }


def installed_candidate_identity() -> dict[str, object] | None:
    resource = files("moss_transcribe_diarize").joinpath("build_candidate.json")
    if not resource.is_file():
        return None
    payload = json.loads(resource.read_text(encoding="utf-8"))
    required = ("git_sha", "git_tree", "uv_lock_sha256")
    if (
        not isinstance(payload, dict)
        or any(not isinstance(payload.get(key), str) for key in required)
        or not isinstance(payload.get("fixtures"), dict)
        or any(not isinstance(value, str) for value in payload["fixtures"].values())
    ):
        raise RuntimeError("Installed candidate identity is malformed.")
    return {**{key: payload[key] for key in required}, "fixtures": dict(payload["fixtures"])}


def installer_owned_empty_record(filename: str) -> bool:
    return filename.endswith(".dist-info/RECORD") or (
        "/__pycache__/" in filename and filename.endswith(".pyc")
    )


def installed_record_identity() -> dict[str, object]:
    """Verify the installed distribution against its own wheel RECORD."""

    package = distribution("moss-transcribe-diarize")
    text = package.read_text("RECORD")
    if text is None:
        raise RuntimeError("Installed candidate RECORD is missing.")
    verified = 0
    records = list(csv.reader(io.StringIO(text)))
    for filename, digest, size in records:
        if not digest:
            if not installer_owned_empty_record(filename):
                raise RuntimeError("Only RECORD or installer-generated bytecode may omit a digest.")
            continue
        algorithm, expected = digest.split("=", 1)
        if algorithm != "sha256":
            raise RuntimeError("Installed candidate RECORD uses a non-sha256 digest.")
        payload = package.locate_file(filename).read_bytes()
        actual = base64.urlsafe_b64encode(hashlib.sha256(payload).digest()).decode().rstrip("=")
        if actual != expected or len(payload) != int(size):
            raise RuntimeError(f"Installed candidate RECORD mismatch: {filename}")
        verified += 1
    return {
        "record_verified": True,
        "record_entries_verified": verified,
        "record_projection_sha256": record_projection_sha256(records),
    }


def publish_candidate_manifest(
    stage_path: Path,
    final_path: Path,
    payload: dict[str, object],
) -> None:
    """Fully write one private candidate manifest, then publish it without replacement."""

    if stage_path.parent != final_path.parent:
        raise ValueError("Candidate manifest stage and final path must share a directory.")
    encoded = (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")
    fd = -1
    try:
        fd = os.open(stage_path, os.O_WRONLY | os.O_TRUNC)
        view = memoryview(encoded)
        while view:
            written = os.write(fd, view)
            if written <= 0:
                raise OSError("Candidate manifest write made no progress.")
            view = view[written:]
        os.fsync(fd)
        os.close(fd)
        fd = -1
        os.link(stage_path, final_path)
        stage_path.unlink()
        directory = os.open(final_path.parent, os.O_RDONLY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    except BaseException:
        if fd >= 0:
            os.close(fd)
        stage_path.unlink(missing_ok=True)
        raise
